name: mobile_app
description: "A new Flutter project."

version: 1.0.0+4

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  flutter_svg: ^2.0.9
  animated_splash_screen: ^1.3.0
  flutter_riverpod: ^2.4.9
  percent_indicator: ^4.2.3
  expandable_text: ^2.3.0
  flutter_stripe: ^10.0.0
  google_fonts: ^6.1.0
  flutter_custom_clippers: ^2.1.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  dio: ^5.4.0
  image_picker: ^1.0.5
  path_provider: ^2.1.3
  path: ^1.8.3
  flutter_image_compress: ^2.1.0
  image: ^4.1.3
  logger: ^2.0.2+1
  file_picker: ^6.1.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.4
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.1
  fl_chart: ^0.66.2
  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.1.0
  flutter_pdfview: ^1.3.2
  open_document: ^1.0.7
  syncfusion_flutter_pdfviewer: ^24.2.8
  device_info_plus: ^9.1.2
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  dotted_line: ^3.2.2
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter_icons:
  image_path: "assets/logo.webp"
  ios: true
  android: true
  adaptive_icon_background: "#045ea0"
  adaptive_icon_foreground: "assets/play_store_512.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  test: ^1.25.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login.jpg
    - assets/images/logo/facebook_logo.svg
    - assets/images/logo/google_logo.svg
    - assets/images/logo/otp_login.svg
    - assets/images/register.jpg
    - assets/images/restPassword.jpg
    - assets/images/packageprize/fees.jpg
    - assets/images/memebrshipgroup/bg.jpg
    - assets/images/memebrshipgroup/lab.svg
    - assets/images/memebrshipgroup/groups.svg
    - assets/images/memebrshipgroup/earth.svg
    - assets/images/contactus.jpg
    - assets/home.jpg
    - assets/images/restpwd/otprestpwd.jpg
    - assets/images/restpwd/restpwd.jpg
    - assets/images/profile/no_profile.png
    - assets/worldMap.png
    #home company images
    - assets/images/home_comany_img/1.jpeg
    - assets/images/home_comany_img/2.jpeg
    - assets/images/home_comany_img/3.jpg
    - assets/images/home_comany_img/4.jpg
    # profile
    - assets/profile_svg.svg
    #SVG
    - assets/svg_list_draver/Group (1).svg
    - assets/svg_list_draver/memebrship.svg
    - assets/svg_list_draver/svgexport-8.svg
    - assets/svg_list_draver/memebrsipProfile.svg
    #Progress Bar
    - assets/progressBar/progress.svg
    #stage 04
    - assets/Arrow 4.svg
    - assets/Group 2140.svg
    - assets/icon _calendar_.svg
    #Contact Us
    - assets/contactUs-Svg.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Adamina
      fonts:
        - asset: assets/fonts/Adamina-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
